
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "WarUnit.sol";

contract Warrior is WarUnit{   
    constructor (BaseStation baseStation) WarUnit(baseStation) public Accept{
        attackPoints = 2;
        defencePoints = 2;
    }

function GetAttackPoints() external override Accept returns(uint){
        return attackPoints;
}

}